# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
